export type AnswerValue = string | string[];

export type WorkflowQuestion = {
  id: string;
  dimension: string;
  title: string;
  type: "select" | "multi" | "date" | "number" | "duration" | "calculated";
  options?: string[];
  unitOptions?: string[];
  showWhen?: (answers: Record<string, AnswerValue>) => boolean;
};

export const bodyRegions = [
  "Pescoço/região cervical",
  "Região torácica/dorsal superior",
  "Região lombar/lombossacral",
  "Ombro",
  "Braço",
  "Cotovelo",
  "Antebraço",
  "Punho",
  "Mão",
  "Dedos da mão",
  "Quadril/região glútea",
  "Coxa",
  "Joelho",
  "Perna",
  "Tornozelo",
  "Pé",
  "Dedos do pé",
];

export const movements = [
  "Flexão",
  "Extensão",
  "Rotação",
  "Inclinação",
  "Elevação",
  "Abdução",
  "Adução",
  "Pronação",
  "Supinação",
  "Preensão",
  "Pinça",
  "Digitação",
  "Agachamento",
  "Ajoelhamento",
  "Caminhada",
  "Permanência em pé",
  "Alcance acima do ombro",
];

export const conditionCatalog = [
  "Síndrome cervicobraquial",
  "Hérnia ou transtorno de disco cervical",
  "Distensão musculoligamentar lombar",
  "Hérnia ou transtorno de disco lombar",
  "Tendinopatia do manguito rotador",
  "Ruptura do manguito rotador",
  "Bursite subacromial",
  "Tendinopatia da cabeça longa do bíceps",
  "Epicondilite lateral",
  "Epicondilite medial",
  "Bursite olecraniana",
  "Síndrome do túnel cubital",
  "Síndrome do pronador redondo",
  "Síndrome do túnel do carpo",
  "Síndrome do canal de Guyon",
  "Tenossinovite de De Quervain",
  "Tenossinovite dos flexores ou extensores de punho e mão",
  "Dedo em gatilho",
  "Tendinopatia glútea / síndrome dolorosa trocantérica",
  "Bursite pré-patelar",
  "Tendinopatia patelar",
  "Tendinopatia do tendão de Aquiles",
  "Fasciopatia plantar",
  "Tendinopatia dos fibulares ou do tibial posterior",
  "Outra condição",
];

export const structures = [
  "Músculo",
  "Tendão",
  "Ligamento",
  "Nervo",
  "Articulação",
  "Disco",
  "Osso",
  "Bursa",
  "Fáscia",
  "Não informado",
];

export const conditionQuestions: WorkflowQuestion[] = [
  {
    id: "COND01",
    dimension: "Identificação",
    title: "Qual é a natureza da condição alegada?",
    type: "select",
    options: [
      "Lesão traumática por esforço",
      "Doença/distúrbio musculoesquelético",
      "Sintoma sem diagnóstico definido",
      "Em investigação",
    ],
  },
  {
    id: "COND02",
    dimension: "Confiabilidade",
    title: "Existe um diagnóstico específico definido?",
    type: "select",
    options: ["Sim", "Não", "Em investigação"],
  },
  {
    id: "COND03",
    dimension: "Identificação",
    title: "Qual condição específica foi informada?",
    type: "select",
    options: conditionCatalog,
    showWhen: (a) => a.COND02 === "Sim",
  },
  {
    id: "COND04",
    dimension: "Compatibilidade anatômica",
    title: "Qual região corporal é afetada?",
    type: "multi",
    options: bodyRegions,
  },
  {
    id: "COND05",
    dimension: "Compatibilidade anatômica",
    title: "Qual lado é afetado?",
    type: "select",
    options: ["Direito", "Esquerdo", "Ambos", "Central"],
    showWhen: (a) =>
      Array.isArray(a.COND04) &&
      (a.COND04 as string[]).some(
        (r) =>
          !r.includes("cervical") &&
          !r.includes("torácica") &&
          !r.includes("lombar"),
      ),
  },
  {
    id: "COND06",
    dimension: "Compatibilidade anatômica",
    title: "Quais estruturas são afetadas?",
    type: "multi",
    options: structures,
  },
  {
    id: "COND07",
    dimension: "Compatibilidade biomecânica",
    title: "Quais movimentos são comprometidos ou agravam os sintomas?",
    type: "multi",
    options: movements,
    showWhen: (a) => Array.isArray(a.COND04) && a.COND04.length > 0,
  },
  {
    id: "COND08",
    dimension: "Compatibilidade temporal",
    title: "Quando começaram os primeiros sintomas?",
    type: "date",
  },
  {
    id: "COND09",
    dimension: "Compatibilidade temporal",
    title: "O início dos sintomas foi súbito ou gradual?",
    type: "select",
    options: ["Súbito", "Gradual", "Não sabe"],
  },
  {
    id: "COND10",
    dimension: "Compatibilidade temporal",
    title:
      "No início, os sintomas apareceram em relação a qual atividade cadastrada?",
    type: "select",
    options: ["Atividade cadastrada", "Nenhuma", "Não sabe"],
  },
  {
    id: "COND11",
    dimension: "Compatibilidade temporal",
    title: "Em que momento os sintomas geralmente apareciam?",
    type: "select",
    options: [
      "Durante",
      "Logo após",
      "Horas depois",
      "No dia seguinte",
      "Sem relação percebida",
    ],
  },
  {
    id: "COND12",
    dimension: "Resposta à interrupção",
    title: "Interromper a atividade reduzia os sintomas?",
    type: "select",
    options: ["Sim", "Parcialmente", "Não", "Não houve interrupção"],
  },
  {
    id: "COND13",
    dimension: "Resposta à retomada",
    title: "Retomar a atividade aumentava novamente os sintomas?",
    type: "select",
    options: ["Sim", "Parcialmente", "Não", "Não houve retomada"],
    showWhen: (a) => a.COND12 !== "Não houve interrupção",
  },
];

export const activityQuestions: WorkflowQuestion[] = [
  {
    id: "AT01",
    dimension: "Exposição temporal",
    title: "Quando começou a realizar essa atividade?",
    type: "date",
  },
  {
    id: "AT02",
    dimension: "Exposição temporal",
    title: "Quando deixou de realizar essa atividade?",
    type: "date",
  },
  {
    id: "AT03",
    dimension: "Intensidade da exposição",
    title: "Quantos dias por semana realizava a atividade?",
    type: "number",
    unitOptions: ["dias por semana"],
  },
  {
    id: "AT04",
    dimension: "Intensidade da exposição",
    title: "Quantas vezes a atividade era realizada por jornada?",
    type: "number",
    unitOptions: ["execuções por jornada"],
  },
  {
    id: "AT05",
    dimension: "Intensidade da exposição",
    title: "Quanto tempo durava cada realização?",
    type: "number",
    unitOptions: ["Minutos", "Horas"],
  },
  {
    id: "AT06",
    dimension: "Intensidade da exposição",
    title: "Qual era o tempo total da atividade por jornada?",
    type: "duration",
  },
  {
    id: "AT07",
    dimension: "Intensidade da exposição",
    title: "Havia pausas entre as realizações?",
    type: "select",
    options: ["Não", "Sim"],
  },
  {
    id: "AT07_DURATION",
    dimension: "Intensidade da exposição",
    title: "Informe a duração e a frequência das pausas",
    type: "number",
    unitOptions: ["minutos a cada hora", "minutos por jornada"],
    showWhen: (a) => a.AT07 === "Sim",
  },
  {
    id: "AT08",
    dimension: "Intensidade da exposição",
    title: "A atividade alternava com outra atividade?",
    type: "select",
    options: ["Sim", "Não"],
  },
  {
    id: "AT09",
    dimension: "Compatibilidade anatômica",
    title: "Quais regiões corporais eram exigidas pela atividade?",
    type: "multi",
    options: bodyRegions,
  },
  {
    id: "AT10",
    dimension: "Compatibilidade anatômica",
    title: "Qual lado era predominantemente utilizado?",
    type: "select",
    options: ["Direito", "Esquerdo", "Ambos", "Alternado"],
    showWhen: (a) => Array.isArray(a.AT09) && a.AT09.length > 0,
  },
  {
    id: "AT11",
    dimension: "Compatibilidade biomecânica",
    title: "Quais movimentos eram realizados?",
    type: "multi",
    options: movements,
    showWhen: (a) => Array.isArray(a.AT09) && a.AT09.length > 0,
  },
  {
    id: "AT12",
    dimension: "Compatibilidade biomecânica",
    title: "A atividade exigia postura fora da posição neutra?",
    type: "select",
    options: ["Sim", "Não", "Não sabe"],
  },
  {
    id: "AT13",
    dimension: "Compatibilidade biomecânica",
    title: "Qual postura fora da posição neutra era adotada?",
    type: "multi",
    options: [
      "Tronco flexionado",
      "Tronco rodado",
      "Braços elevados",
      "Punho desviado",
      "Agachado",
      "Ajoelhado",
      "Pescoço inclinado",
    ],
    showWhen: (a) => a.AT12 === "Sim",
  },
  {
    id: "AT14",
    dimension: "Intensidade da exposição",
    title: "Por quanto tempo essa postura era mantida sem mudança?",
    type: "number",
    unitOptions: ["Segundos", "Minutos"],
    showWhen: (a) => a.AT12 === "Sim",
  },
  {
    id: "AT15",
    dimension: "Compatibilidade biomecânica",
    title: "Havia movimentos repetitivos?",
    type: "select",
    options: ["Sim", "Não", "Não sabe"],
  },
  {
    id: "AT16",
    dimension: "Compatibilidade biomecânica",
    title: "Qual movimento era repetido?",
    type: "multi",
    options: movements,
    showWhen: (a) => a.AT15 === "Sim",
  },
  {
    id: "AT17",
    dimension: "Intensidade da exposição",
    title: "Quantas repetições eram realizadas?",
    type: "number",
    unitOptions: ["Por minuto", "Por hora", "Por ciclo"],
    showWhen: (a) => a.AT15 === "Sim",
  },
  {
    id: "AT18",
    dimension: "Compatibilidade biomecânica",
    title: "A atividade exigia aplicação de força?",
    type: "select",
    options: ["Sim", "Não"],
  },
  {
    id: "AT19",
    dimension: "Compatibilidade biomecânica",
    title: "Qual tipo de força era aplicada?",
    type: "multi",
    options: [
      "Levantar",
      "Baixar",
      "Carregar",
      "Empurrar",
      "Puxar",
      "Segurar",
      "Apertar",
      "Girar",
    ],
    showWhen: (a) => a.AT18 === "Sim",
  },
  {
    id: "AT20",
    dimension: "Intensidade da exposição",
    title: "Qual era o peso ou a resistência aproximada?",
    type: "number",
    unitOptions: ["Quilogramas"],
    showWhen: (a) => a.AT18 === "Sim",
  },
  {
    id: "AT21",
    dimension: "Intensidade da exposição",
    title: "Quantas vezes a força era aplicada?",
    type: "number",
    unitOptions: ["Por minuto", "Por hora", "Por jornada"],
    showWhen: (a) => a.AT18 === "Sim",
  },
  {
    id: "AT22",
    dimension: "Compatibilidade biomecânica",
    title: "A carga era manipulada com uma ou duas mãos?",
    type: "select",
    options: ["Uma", "Duas", "Variava"],
    showWhen: (a) => a.AT18 === "Sim",
  },
  {
    id: "AT23",
    dimension: "Compatibilidade biomecânica",
    title: "A carga permanecia próxima ao corpo?",
    type: "select",
    options: ["Sempre", "Às vezes", "Nunca"],
    showWhen: (a) => a.AT18 === "Sim",
  },
  {
    id: "AT24",
    dimension: "Compatibilidade biomecânica",
    title: "Havia vibração?",
    type: "select",
    options: ["Não", "Mãos e braços", "Corpo inteiro"],
  },
  {
    id: "AT25",
    dimension: "Intensidade da exposição",
    title: "Por quanto tempo havia exposição à vibração por jornada?",
    type: "number",
    unitOptions: ["Minutos", "Horas"],
    showWhen: (a) => a.AT24 !== undefined && a.AT24 !== "Não",
  },
  {
    id: "AT26",
    dimension: "Mudança de exposição",
    title: "A exigência da atividade mudou durante o período avaliado?",
    type: "select",
    options: ["Aumentou", "Diminuiu", "Não mudou"],
  },
  {
    id: "AT27",
    dimension: "Mudança de exposição",
    title: "O que mudou na exigência da atividade?",
    type: "multi",
    options: [
      "Frequência",
      "Duração",
      "Repetição",
      "Força",
      "Peso",
      "Postura",
      "Vibração",
    ],
    showWhen: (a) => a.AT26 === "Aumentou" || a.AT26 === "Diminuiu",
  },
  {
    id: "AT28",
    dimension: "Compatibilidade temporal",
    title: "Quando a mudança na exigência ocorreu?",
    type: "date",
    showWhen: (a) => a.AT26 === "Aumentou" || a.AT26 === "Diminuiu",
  },
];

export const timelineQuestions: WorkflowQuestion[] = [
  {
    id: "LT01",
    dimension: "Compatibilidade temporal",
    title: "Os sintomas começaram antes ou depois do início da atividade?",
    type: "calculated",
  },
  {
    id: "LT02",
    dimension: "Compatibilidade temporal",
    title: "Tempo entre o início da atividade e os primeiros sintomas",
    type: "calculated",
  },
  {
    id: "LT03",
    dimension: "Compatibilidade temporal",
    title:
      "Houve aumento da exposição antes do início ou da piora dos sintomas?",
    type: "select",
    options: ["Sim", "Não", "Não sabe"],
    showWhen: (a) => a.AT26 === "Aumentou",
  },
  {
    id: "LT04",
    dimension: "Compatibilidade temporal",
    title:
      "Quanto tempo depois desse aumento os sintomas começaram ou pioraram?",
    type: "number",
    unitOptions: ["Dias", "Semanas", "Meses"],
    showWhen: (a) => a.LT03 === "Sim",
  },
  {
    id: "LT05",
    dimension: "Resposta à interrupção",
    title: "Houve período sem realizar a atividade?",
    type: "select",
    options: ["Sim", "Não"],
  },
  {
    id: "LT06",
    dimension: "Resposta à interrupção",
    title: "Quanto tempo durou esse período sem realizar a atividade?",
    type: "number",
    unitOptions: ["Dias", "Semanas", "Meses"],
    showWhen: (a) => a.LT05 === "Sim",
  },
  {
    id: "LT07",
    dimension: "Resposta à interrupção",
    title: "Durante o período sem a atividade, os sintomas mudaram?",
    type: "select",
    options: ["Melhoraram", "Não mudaram", "Pioraram", "Não sabe"],
    showWhen: (a) => a.LT05 === "Sim",
  },
  {
    id: "LT08",
    dimension: "Resposta à retomada",
    title: "A atividade foi retomada?",
    type: "select",
    options: ["Sim", "Não"],
    showWhen: (a) => a.LT05 === "Sim",
  },
  {
    id: "LT09",
    dimension: "Resposta à retomada",
    title: "Após a retomada, os sintomas mudaram?",
    type: "select",
    options: ["Melhoraram", "Não mudaram", "Pioraram", "Não sabe"],
    showWhen: (a) => a.LT08 === "Sim",
  },
  {
    id: "LT10",
    dimension: "Resposta à retomada",
    title: "Quanto tempo depois da retomada ocorreu essa mudança?",
    type: "select",
    options: ["Imediatamente", "Dias", "Semanas", "Meses"],
    showWhen: (a) => a.LT08 === "Sim" && a.LT09 !== "Não mudaram",
  },
  {
    id: "LT11",
    dimension: "Compatibilidade temporal",
    title: "Os sintomas começaram depois que a atividade já havia terminado?",
    type: "calculated",
  },
  {
    id: "LT12",
    dimension: "Consistência temporal",
    title: "Existiam períodos de sintomas sem exposição à atividade?",
    type: "select",
    options: ["Sim", "Não", "Não sabe"],
  },
];

export const sectorsByCompany: Record<string, string[]> = {
  "Saúde Tech": ["Operações", "Logística", "Administrativo"],
  UFLAniana: ["Tecnologia da Informação", "Atendimento", "Manutenção"],
  "Nova Safra": ["Expedição", "Produção", "Qualidade"],
  "Logis Minas": ["Armazém", "Transporte", "Conferência"],
};
